CREATE DATABASE IF NOT EXISTS bewell_db;

USE bewell_db;

DROP TABLE IF EXISTS submissionSymptoms;
DROP TABLE IF EXISTS submissions;
DROP TABLE IF EXISTS symptoms;
DROP TABLE IF EXISTS flights;
DROP TABLE IF EXISTS airlines;
DROP TABLE IF EXISTS illnesses;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS submissionSymptom;
DROP TABLE IF EXISTS submission;
DROP TABLE IF EXISTS symptom;
DROP TABLE IF EXISTS flight;
DROP TABLE IF EXISTS airline;
DROP TABLE IF EXISTS illness;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS SubmissionSymptoms;
DROP TABLE IF EXISTS Submissions;
DROP TABLE IF EXISTS Symptoms;
DROP TABLE IF EXISTS Flights;
DROP TABLE IF EXISTS Airlines;
DROP TABLE IF EXISTS Illnesses;
DROP TABLE IF EXISTS `Users`;
DROP TABLE IF EXISTS SubmissionsRequest;
DROP TABLE IF EXISTS SubmissionsRequests;

CREATE TABLE IF NOT EXISTS `Users`
(userID INTEGER NOT NULL AUTO_INCREMENT
, firstname VARCHAR(45) NOT NULL
, lastname VARCHAR(45) NOT NULL
, email VARCHAR(100) NOT NULL
, PRIMARY KEY (userID)
);

CREATE TABLE IF NOT EXISTS Illnesses
(illnessID INTEGER NOT NULL AUTO_INCREMENT
, illnessName VARCHAR(45) NOT NULL
, PRIMARY KEY (illnessID)
);

CREATE TABLE IF NOT EXISTS Airlines
(airlineID INTEGER NOT NULL AUTO_INCREMENT
, airlineName VARCHAR(45) NOT NULL
, PRIMARY KEY (airlineID)
);

CREATE TABLE IF NOT EXISTS Flights
(flightID INTEGER NOT NULL AUTO_INCREMENT
, flightDate DATE NOT NULL
, airlineID INTEGER NOT NULL
, flightNumber VARCHAR(45) NOT NULL
, PRIMARY KEY (flightID)
, FOREIGN KEY (airlineID) REFERENCES Airlines(airlineID)
);

CREATE TABLE IF NOT EXISTS Symptoms
(symptomID INTEGER NOT NULL
, symptomName VARCHAR(45) NOT NULL
, PRIMARY KEY (symptomID)
);

CREATE TABLE IF NOT EXISTS Submissions
(submissionID INTEGER NOT NULL AUTO_INCREMENT
, userID INTEGER NOT NULL
, flightID INTEGER NOT NULL
, illnessID INTEGER NOT NULL
, submissionDate DATE NOT NULL
, PRIMARY KEY (submissionID)
, FOREIGN KEY (userID) REFERENCES `Users`(userID)
, FOREIGN KEY (flightID) REFERENCES Flights(flightID)
, FOREIGN KEY (illnessID) REFERENCES Illnesses(illnessID)
);

CREATE TABLE IF NOT EXISTS SubmissionSymptoms
(submissionSymptonID INTEGER NOT NULL AUTO_INCREMENT
, submissionID INTEGER NOT NULL
, symptomID INTEGER NOT NULL
, PRIMARY KEY (submissionSymptonID)
, FOREIGN KEY (submissionID) REFERENCES Submissions(submissionID)
, FOREIGN KEY (symptomID) REFERENCES Symptoms(symptomID)
);
